'''try:
    dajfo;iadjf;A
    
except:
    print("에러발생")  #의도적으로 에러 처리를 해 준다., try 문에서 에러가 발생하면 except 문을 실행하여 내가 원하는 에러발생문을 출력
'''

'''try:
    dajfilask;fab
except:
    pass #그러면 에러가 발생해도 아무것도 하지 않고 다음 줄을 그대로 출력한다.
print("에러 무시")'''

#에러의 원인을 알고 싶은 경우
try:
    djafadfajd
except Exception as e:
    print("에러 발생 원인:",e)